load('Messergebnisse\phiK45_rawValues');
phiK45_x1_raw = x1SignedValues;
phiK45_x2_raw = x2SignedValues;
phiK45_y1_raw = y1SignedValues;
phiK45_y2_raw = y2SignedValues;
load('Messergebnisse\phiK30_rawValues');
phiK30_x1_raw = x1SignedValues;
phiK30_x2_raw = x2SignedValues;
phiK30_y1_raw = y1SignedValues;
phiK30_y2_raw = y2SignedValues;
load('Messergebnisse\phiK15_rawValues');
phiK15_x1_raw = x1SignedValues;
phiK15_x2_raw = x2SignedValues;
phiK15_y1_raw = y1SignedValues;
phiK15_y2_raw = y2SignedValues;
load('Messergebnisse\phiK0_rawValues');
phiK0_x1_raw = x1SignedValues;
phiK0_x2_raw = x2SignedValues;
phiK0_y1_raw = y1SignedValues;
phiK0_y2_raw = y2SignedValues;
load('Messergebnisse\phiK-15_rawValues');
phiKm15_x1_raw = x1SignedValues;
phiKm15_x2_raw = x2SignedValues;
phiKm15_y1_raw = y1SignedValues;
phiKm15_y2_raw = y2SignedValues;
load('Messergebnisse\phiK-30_rawValues');
phiKm30_x1_raw = x1SignedValues;
phiKm30_x2_raw = x2SignedValues;
phiKm30_y1_raw = y1SignedValues;
phiKm30_y2_raw = y2SignedValues;
load('Messergebnisse\phiK-45_rawValues');
phiKm45_x1_raw = x1SignedValues;
phiKm45_x2_raw = x2SignedValues;
phiKm45_y1_raw = y1SignedValues;
phiKm45_y2_raw = y2SignedValues;
load('Messergebnisse\polyApproximation');

phiK = [-45 -30 -15 0 15 30 45];
m = 10000;
deltaT = 5e-3;
time = 0:deltaT:9999*deltaT;
%Calcualte Acceleration values using the polynom approximation
phiK45_x1_acc = x1Pol1.p1 * phiK45_x1_raw + x1Pol1.p2;
phiK45_x2_acc = x2Pol1.p1 * phiK45_x2_raw + x2Pol1.p2;
phiK45_y1_acc = y1Pol1.p1 * phiK45_y1_raw + y1Pol1.p2;
phiK45_y2_acc = y2Pol1.p1 * phiK45_y2_raw + y2Pol1.p2;
phiK30_x1_acc = x1Pol1.p1 * phiK30_x1_raw + x1Pol1.p2;
phiK30_x2_acc = x2Pol1.p1 * phiK30_x2_raw + x2Pol1.p2;
phiK30_y1_acc = y1Pol1.p1 * phiK30_y1_raw + y1Pol1.p2;
phiK30_y2_acc = y2Pol1.p1 * phiK30_y2_raw + y2Pol1.p2;
phiK15_x1_acc = x1Pol1.p1 * phiK15_x1_raw + x1Pol1.p2;
phiK15_x2_acc = x2Pol1.p1 * phiK15_x2_raw + x2Pol1.p2;
phiK15_y1_acc = y1Pol1.p1 * phiK15_y1_raw + y1Pol1.p2;
phiK15_y2_acc = y2Pol1.p1 * phiK15_y2_raw + y2Pol1.p2;
phiK0_x1_acc = x1Pol1.p1 * phiK0_x1_raw + x1Pol1.p2;
phiK0_x2_acc = x2Pol1.p1 * phiK0_x2_raw + x2Pol1.p2;
phiK0_y1_acc = y1Pol1.p1 * phiK0_y1_raw + y1Pol1.p2;
phiK0_y2_acc = y2Pol1.p1 * phiK0_y2_raw + y2Pol1.p2;
phiKm15_x1_acc = x1Pol1.p1 * phiKm15_x1_raw + x1Pol1.p2;
phiKm15_x2_acc = x2Pol1.p1 * phiKm15_x2_raw + x2Pol1.p2;
phiKm15_y1_acc = y1Pol1.p1 * phiKm15_y1_raw + y1Pol1.p2;
phiKm15_y2_acc = y2Pol1.p1 * phiKm15_y2_raw + y2Pol1.p2;
phiKm30_x1_acc = x1Pol1.p1 * phiKm30_x1_raw + x1Pol1.p2;
phiKm30_x2_acc = x2Pol1.p1 * phiKm30_x2_raw + x2Pol1.p2;
phiKm30_y1_acc = y1Pol1.p1 * phiKm30_y1_raw + y1Pol1.p2;
phiKm30_y2_acc = y2Pol1.p1 * phiKm30_y2_raw + y2Pol1.p2;
phiKm45_x1_acc = x1Pol1.p1 * phiKm45_x1_raw + x1Pol1.p2;
phiKm45_x2_acc = x2Pol1.p1 * phiKm45_x2_raw + x2Pol1.p2;
phiKm45_y1_acc = y1Pol1.p1 * phiKm45_y1_raw + y1Pol1.p2;
phiKm45_y2_acc = y2Pol1.p1 * phiKm45_y2_raw + y2Pol1.p2;
%Calculate the target Values
phiK45_x_target = sind(45)*9.81 * ones(1,m);
phiK45_y_target = -cosd(45)*9.81 * ones(1,m);
phiK30_x_target = sind(30)*9.81 * ones(1,m);
phiK30_y_target = -cosd(30)*9.81 * ones(1,m);
phiK15_x_target = sind(15)*9.81 * ones(1,m);
phiK15_y_target = -cosd(15)*9.81 * ones(1,m);
phiK0_x_target  = sind(0)*9.81 * ones(1,m);
phiK0_y_target  = -cosd(0)*9.81 * ones(1,m);
phiKm15_x_target = sind(-15)*9.81 * ones(1,m);
phiKm15_y_target = -cosd(-15)*9.81 * ones(1,m);
phiKm30_x_target = sind(-30)*9.81 * ones(1,m);
phiKm30_y_target = -cosd(-30)*9.81 * ones(1,m);
phiKm45_x_target = sind(-45)*9.81 * ones(1,m);
phiKm45_y_target = -cosd(-45)*9.81 * ones(1,m);
%Calculate the mean Values
phiK45_x1_mean = mean(phiK45_x1_acc) * ones(1,m);
phiK45_x2_mean = mean(phiK45_x2_acc) * ones(1,m);
phiK45_y1_mean = mean(phiK45_y1_acc) * ones(1,m);
phiK45_y2_mean = mean(phiK45_y2_acc) * ones(1,m);
phiK30_x1_mean = mean(phiK30_x1_acc) * ones(1,m);
phiK30_x2_mean = mean(phiK30_x2_acc) * ones(1,m);
phiK30_y1_mean = mean(phiK30_y1_acc) * ones(1,m);
phiK30_y2_mean = mean(phiK30_y2_acc) * ones(1,m);
phiK15_x1_mean = mean(phiK15_x1_acc) * ones(1,m);
phiK15_x2_mean = mean(phiK15_x2_acc) * ones(1,m);
phiK15_y1_mean = mean(phiK15_y1_acc) * ones(1,m);
phiK15_y2_mean = mean(phiK15_y2_acc) * ones(1,m);
phiK0_x1_mean = mean(phiK0_x1_acc) * ones(1,m);
phiK0_x2_mean = mean(phiK0_x2_acc) * ones(1,m);
phiK0_y1_mean = mean(phiK0_y1_acc) * ones(1,m);
phiK0_y2_mean = mean(phiK0_y2_acc) * ones(1,m);
phiKm15_x1_mean = mean(phiKm15_x1_acc) * ones(1,m);
phiKm15_x2_mean = mean(phiKm15_x2_acc) * ones(1,m);
phiKm15_y1_mean = mean(phiKm15_y1_acc) * ones(1,m);
phiKm15_y2_mean = mean(phiKm15_y2_acc) * ones(1,m);
phiKm30_x1_mean = mean(phiKm30_x1_acc) * ones(1,m);
phiKm30_x2_mean = mean(phiKm30_x2_acc) * ones(1,m);
phiKm30_y1_mean = mean(phiKm30_y1_acc) * ones(1,m);
phiKm30_y2_mean = mean(phiKm30_y2_acc) * ones(1,m);
phiKm45_x1_mean = mean(phiKm45_x1_acc) * ones(1,m);
phiKm45_x2_mean = mean(phiKm45_x2_acc) * ones(1,m);
phiKm45_y1_mean = mean(phiKm45_y1_acc) * ones(1,m);
phiKm45_y2_mean = mean(phiKm45_y2_acc) * ones(1,m);
%Calculate the variance and the standard deviation
phiK45_x1_var = var(phiK45_x1_acc);
phiK45_x2_var = var(phiK45_x2_acc);
phiK45_y1_var = var(phiK45_y1_acc);
phiK45_y2_var = var(phiK45_y2_acc);
phiK45_x1_sd  = sqrt(phiK45_x1_var);
phiK45_x2_sd  = sqrt(phiK45_x2_var);
phiK45_y1_sd  = sqrt(phiK45_y1_var);
phiK45_y2_sd  = sqrt(phiK45_y2_var);
phiK30_x1_var = var(phiK30_x1_acc);
phiK30_x2_var = var(phiK30_x2_acc);
phiK30_y1_var = var(phiK30_y1_acc);
phiK30_y2_var = var(phiK30_y2_acc);
phiK30_x1_sd  = sqrt(phiK30_x1_var);
phiK30_x2_sd  = sqrt(phiK30_x2_var);
phiK30_y1_sd  = sqrt(phiK30_y1_var);
phiK30_y2_sd  = sqrt(phiK30_y2_var);
phiK15_x1_var = var(phiK15_x1_acc);
phiK15_x2_var = var(phiK15_x2_acc);
phiK15_y1_var = var(phiK15_y1_acc);
phiK15_y2_var = var(phiK15_y2_acc);
phiK15_x1_sd  = sqrt(phiK15_x1_var);
phiK15_x2_sd  = sqrt(phiK15_x2_var);
phiK15_y1_sd  = sqrt(phiK15_y1_var);
phiK15_y2_sd  = sqrt(phiK15_y2_var);
phiK0_x1_var = var(phiK0_x1_acc);
phiK0_x2_var = var(phiK0_x2_acc);
phiK0_y1_var = var(phiK0_y1_acc);
phiK0_y2_var = var(phiK0_y2_acc);
phiK0_x1_sd  = sqrt(phiK0_x1_var);
phiK0_x2_sd  = sqrt(phiK0_x2_var);
phiK0_y1_sd  = sqrt(phiK0_y1_var);
phiK0_y2_sd  = sqrt(phiK0_y2_var);
phiKm15_x1_var = var(phiKm15_x1_acc);
phiKm15_x2_var = var(phiKm15_x2_acc);
phiKm15_y1_var = var(phiKm15_y1_acc);
phiKm15_y2_var = var(phiKm15_y2_acc);
phiKm15_x1_sd  = sqrt(phiKm15_x1_var);
phiKm15_x2_sd  = sqrt(phiKm15_x2_var);
phiKm15_y1_sd  = sqrt(phiKm15_y1_var);
phiKm15_y2_sd  = sqrt(phiKm15_y2_var);
phiKm30_x1_var = var(phiKm30_x1_acc);
phiKm30_x2_var = var(phiKm30_x2_acc);
phiKm30_y1_var = var(phiKm30_y1_acc);
phiKm30_y2_var = var(phiKm30_y2_acc);
phiKm30_x1_sd  = sqrt(phiKm30_x1_var);
phiKm30_x2_sd  = sqrt(phiKm30_x2_var);
phiKm30_y1_sd  = sqrt(phiKm30_y1_var);
phiKm30_y2_sd  = sqrt(phiKm30_y2_var);
phiKm45_x1_var = var(phiKm45_x1_acc);
phiKm45_x2_var = var(phiKm45_x2_acc);
phiKm45_y1_var = var(phiKm45_y1_acc);
phiKm45_y2_var = var(phiKm45_y2_acc);
phiKm45_x1_sd  = sqrt(phiKm45_x1_var);
phiKm45_x2_sd  = sqrt(phiKm45_x2_var);
phiKm45_y1_sd  = sqrt(phiKm45_y1_var);
phiKm45_y2_sd  = sqrt(phiKm45_y2_var);
%Plot the values with phiK = 45
figure;
plot(time, phiK45_x1_acc, time, phiK45_x_target, time, phiK45_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = 45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK45_X1_acceleration', '-depsc');
figure;
plot(time, phiK45_x2_acc, time, phiK45_x_target, time, phiK45_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = 45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK45_X2_acceleration', '-depsc');
figure;
plot(time, phiK45_y1_acc, time, phiK45_y_target, time, phiK45_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = 45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK45_Y1_acceleration', '-depsc');
figure;
plot(time, phiK45_y2_acc, time, phiK45_y_target, time, phiK45_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = 45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK45_Y2_acceleration', '-depsc');
%Plot the values with phiK = 30
figure;
plot(time, phiK30_x1_acc, time, phiK30_x_target, time, phiK30_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = 30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK30_X1_acceleration', '-depsc');
figure;
plot(time, phiK30_x2_acc, time, phiK30_x_target, time, phiK30_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = 30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK30_X2_acceleration', '-depsc');
figure;
plot(time, phiK30_y1_acc, time, phiK30_y_target, time, phiK30_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = 30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK30_Y1_acceleration', '-depsc');
figure;
plot(time, phiK30_y2_acc, time, phiK30_y_target, time, phiK30_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = 30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK30_Y2_acceleration', '-depsc');
%Plot the values with phiK = 15
figure;
plot(time, phiK15_x1_acc, time, phiK15_x_target, time, phiK15_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = 15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK15_X1_acceleration', '-depsc');
figure;
plot(time, phiK15_x2_acc, time, phiK15_x_target, time, phiK15_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = 15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK15_X2_acceleration', '-depsc');
figure;
plot(time, phiK15_y1_acc, time, phiK15_y_target, time, phiK15_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = 15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK15_Y1_acceleration', '-depsc');
figure;
plot(time, phiK15_y2_acc, time, phiK15_y_target, time, phiK15_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = 15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK15_Y2_acceleration', '-depsc');
%Plot the values with phiK = 0
figure;
plot(time, phiK0_x1_acc, time, phiK0_x_target, time, phiK0_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = 0');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK0_X1_acceleration', '-depsc');
figure;
plot(time, phiK0_x2_acc, time, phiK0_x_target, time, phiK0_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = 0');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK0_X2_acceleration', '-depsc');
figure;
plot(time, phiK0_y1_acc, time, phiK0_y_target, time, phiK0_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = 0');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK0_Y1_acceleration', '-depsc');
figure;
plot(time, phiK0_y2_acc, time, phiK0_y_target, time, phiK0_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = 0');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiK0_Y2_acceleration', '-depsc');
%Plot the values with phiK = -15
figure;
plot(time, phiKm15_x1_acc, time, phiKm15_x_target, time, phiKm15_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = -15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm15_X1_acceleration', '-depsc');
figure;
plot(time, phiKm15_x2_acc, time, phiKm15_x_target, time, phiKm15_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = -15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm15_X2_acceleration', '-depsc');
figure;
plot(time, phiKm15_y1_acc, time, phiKm15_y_target, time, phiKm15_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = -15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm15_Y1_acceleration', '-depsc');
figure;
plot(time, phiKm15_y2_acc, time, phiKm15_y_target, time, phiKm15_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = -15');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm15_Y2_acceleration', '-depsc');
%Plot the values with phiK = -30
figure;
plot(time, phiKm30_x1_acc, time, phiKm30_x_target, time, phiKm30_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = -30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm30_X1_acceleration', '-depsc');
figure;
plot(time, phiKm30_x2_acc, time, phiKm30_x_target, time, phiKm30_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = -30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm30_X2_acceleration', '-depsc');
figure;
plot(time, phiKm30_y1_acc, time, phiKm30_y_target, time, phiKm30_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = -30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm30_Y1_acceleration', '-depsc');
figure;
plot(time, phiKm30_y2_acc, time, phiKm30_y_target, time, phiKm30_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = -30');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm30_Y2_acceleration', '-depsc');
%Plot the values with phiK = -45
figure;
plot(time, phiKm45_x1_acc, time, phiKm45_x_target, time, phiKm45_x1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X1 in m/s^2');
title('Beschleunigung von X1 bei \phi_K = -45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm45_X1_acceleration', '-depsc');
figure;
plot(time, phiKm45_x2_acc, time, phiKm45_x_target, time, phiKm45_x2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung X2 in m/s^2');
title('Beschleunigung von X2 bei \phi_K = -45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm45_X2_acceleration', '-depsc');
figure;
plot(time, phiKm45_y1_acc, time, phiKm45_y_target, time, phiKm45_y1_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y1 in m/s^2');
title('Beschleunigung von Y1 bei \phi_K = -45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm45_Y1_acceleration', '-depsc');
figure;
plot(time, phiKm45_y2_acc, time, phiKm45_y_target, time, phiKm45_y2_mean);
grid; xlabel('Zeit in Sekunden'); ylabel('Beschleunigung Y2 in m/s^2');
title('Beschleunigung von Y2 bei \phi_K = -45');
legend('Beschleunigung', 'Sollwert', 'Mittelwert');
print('phiKm45_Y2_acceleration', '-depsc');